/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TimeApp;

import static java.lang.Thread.sleep;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author debuayanri_sd2022
 */
public class FourNOne_TimeApp extends javax.swing.JFrame {

    /**
     * Creates new form mAIN
     */
    public FourNOne_TimeApp() {

        initComponents();

    }
    static boolean watch = true;
    static boolean up = true;
    int countup = 0;
    static boolean down = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Jpanel3 = new javax.swing.JPanel();
        downStart = new javax.swing.JButton();
        downStop = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        downMinute = new javax.swing.JTextField();
        downSecond = new javax.swing.JTextField();
        downHour = new javax.swing.JTextField();
        downLabelStart = new javax.swing.JLabel();
        downLabelStop = new javax.swing.JLabel();
        notify = new javax.swing.JLabel();
        Jpanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCurrentTime = new javax.swing.JLabel();
        Jpanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelStopWatch = new javax.swing.JLabel();
        stopwatchStop = new javax.swing.JButton();
        stopwatchStart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        stopwatchLabelStop = new javax.swing.JLabel();
        stopwatchLabelStart = new javax.swing.JLabel();
        Jpanel4 = new javax.swing.JPanel();
        upStop = new javax.swing.JButton();
        upStart = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        upCount = new javax.swing.JLabel();
        upLabelStart = new javax.swing.JLabel();
        upLabelStop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIME APPLICATION");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 0, 153));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIME APPLICATION");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        Jpanel3.setBackground(new java.awt.Color(255, 204, 255));
        Jpanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        downStart.setBackground(new java.awt.Color(204, 204, 255));
        downStart.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        downStart.setForeground(new java.awt.Color(204, 0, 0));
        downStart.setText("Start");
        downStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downStartActionPerformed(evt);
            }
        });

        downStop.setBackground(new java.awt.Color(255, 255, 204));
        downStop.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        downStop.setForeground(new java.awt.Color(153, 51, 255));
        downStop.setText("Stop");
        downStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downStopActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Count Down");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(255, 255, 255)));

        downMinute.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        downMinute.setForeground(new java.awt.Color(0, 51, 255));
        downMinute.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        downMinute.setText("00");
        downMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downMinuteActionPerformed(evt);
            }
        });

        downSecond.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        downSecond.setForeground(new java.awt.Color(0, 51, 255));
        downSecond.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        downSecond.setText("00");
        downSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downSecondActionPerformed(evt);
            }
        });

        downHour.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        downHour.setForeground(new java.awt.Color(0, 51, 255));
        downHour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        downHour.setText("00");
        downHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downHourActionPerformed(evt);
            }
        });

        downLabelStart.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        downLabelStart.setForeground(new java.awt.Color(204, 0, 0));
        downLabelStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        downLabelStop.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        downLabelStop.setForeground(new java.awt.Color(153, 51, 255));
        downLabelStop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        notify.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        notify.setForeground(new java.awt.Color(255, 51, 255));
        notify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Jpanel3Layout = new javax.swing.GroupLayout(Jpanel3);
        Jpanel3.setLayout(Jpanel3Layout);
        Jpanel3Layout.setHorizontalGroup(
            Jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(downStart)
                .addGap(18, 18, 18)
                .addComponent(downLabelStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(downLabelStop)
                .addGap(18, 18, 18)
                .addComponent(downStop)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel3Layout.createSequentialGroup()
                        .addComponent(downHour, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(notify))
                            .addGroup(Jpanel3Layout.createSequentialGroup()
                                .addComponent(downMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(downSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))))
        );
        Jpanel3Layout.setVerticalGroup(
            Jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downHour, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downStart)
                            .addComponent(downStop)
                            .addComponent(downLabelStart, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(downLabelStop, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(Jpanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notify, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Jpanel2.setBackground(new java.awt.Color(204, 255, 204));
        Jpanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(255, 0, 51));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Current Time");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 204, 0), new java.awt.Color(255, 255, 255)));

        jLabelCurrentTime.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabelCurrentTime.setForeground(new java.awt.Color(0, 153, 0));
        jLabelCurrentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCurrentTime.setText("00:00:00");
        jLabelCurrentTime.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jLabelCurrentTime.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelCurrentTimePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout Jpanel2Layout = new javax.swing.GroupLayout(Jpanel2);
        Jpanel2.setLayout(Jpanel2Layout);
        Jpanel2Layout.setHorizontalGroup(
            Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addComponent(jLabelCurrentTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        Jpanel2Layout.setVerticalGroup(
            Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabelCurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jpanel1.setBackground(new java.awt.Color(204, 255, 255));
        Jpanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Minute");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Second");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(255, 255, 255)));

        jLabelStopWatch.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabelStopWatch.setForeground(new java.awt.Color(0, 51, 255));
        jLabelStopWatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStopWatch.setText("00:00:00");
        jLabelStopWatch.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        stopwatchStop.setBackground(new java.awt.Color(255, 255, 204));
        stopwatchStop.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        stopwatchStop.setForeground(new java.awt.Color(153, 51, 255));
        stopwatchStop.setText("Stop");
        stopwatchStop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stopwatchStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                none(evt);
            }
        });
        stopwatchStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopwatchStopActionPerformed(evt);
            }
        });

        stopwatchStart.setBackground(new java.awt.Color(204, 204, 255));
        stopwatchStart.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        stopwatchStart.setForeground(new java.awt.Color(204, 0, 0));
        stopwatchStart.setText("Start");
        stopwatchStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopwatchStartMouseClicked(evt);
            }
        });
        stopwatchStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopwatchStartActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hour");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(255, 255, 255)));

        stopwatchLabelStop.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        stopwatchLabelStop.setForeground(new java.awt.Color(153, 51, 255));
        stopwatchLabelStop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopwatchLabelStop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stopwatchLabelStart.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        stopwatchLabelStart.setForeground(new java.awt.Color(204, 0, 0));
        stopwatchLabelStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopwatchLabelStart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout Jpanel1Layout = new javax.swing.GroupLayout(Jpanel1);
        Jpanel1.setLayout(Jpanel1Layout);
        Jpanel1Layout.setHorizontalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel1Layout.createSequentialGroup()
                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Jpanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel1Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(jLabelStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jpanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(stopwatchStart)
                        .addGap(18, 18, 18)
                        .addComponent(stopwatchLabelStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stopwatchLabelStop)
                        .addGap(18, 18, 18)
                        .addComponent(stopwatchStop)
                        .addGap(8, 8, 8)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        Jpanel1Layout.setVerticalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopwatchStop)
                    .addComponent(stopwatchStart)
                    .addComponent(stopwatchLabelStart)
                    .addComponent(stopwatchLabelStop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stopwatchLabelStop.getAccessibleContext().setAccessibleParent(stopwatchStart);

        Jpanel4.setBackground(new java.awt.Color(255, 204, 204));
        Jpanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        upStop.setBackground(new java.awt.Color(255, 255, 204));
        upStop.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        upStop.setForeground(new java.awt.Color(153, 51, 255));
        upStop.setText("Stop");
        upStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upStopMouseClicked(evt);
            }
        });
        upStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upStopActionPerformed(evt);
            }
        });

        upStart.setBackground(new java.awt.Color(204, 204, 255));
        upStart.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        upStart.setForeground(new java.awt.Color(204, 0, 0));
        upStart.setText("Start");
        upStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upStartMouseClicked(evt);
            }
        });
        upStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upStartActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Count Up");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(255, 255, 255)));

        upCount.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        upCount.setForeground(new java.awt.Color(0, 51, 255));
        upCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upCount.setText("0");
        upCount.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        upLabelStart.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        upLabelStart.setForeground(new java.awt.Color(204, 0, 0));
        upLabelStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        upLabelStop.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        upLabelStop.setForeground(new java.awt.Color(153, 51, 255));
        upLabelStop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Jpanel4Layout = new javax.swing.GroupLayout(Jpanel4);
        Jpanel4.setLayout(Jpanel4Layout);
        Jpanel4Layout.setHorizontalGroup(
            Jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(upStart)
                .addGap(18, 18, 18)
                .addComponent(upLabelStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(upLabelStop)
                .addGap(31, 31, 31)
                .addComponent(upStop)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel4Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(Jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(upCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        Jpanel4Layout.setVerticalGroup(
            Jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upCount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(Jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upStop)
                    .addComponent(upStart)
                    .addComponent(upLabelStart, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upLabelStop, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jpanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopwatchStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopwatchStopActionPerformed
        watch = false;
        stopwatchStop.setVisible(false);
        stopwatchStart.setVisible(true);
        stopwatchLabelStop.setText("Stop");
        stopwatchLabelStart.setText("");
    }//GEN-LAST:event_stopwatchStopActionPerformed

    private void stopwatchStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopwatchStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopwatchStartActionPerformed

    private void downStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downStartActionPerformed
        // TODO add your handling code here:
        downStart.setVisible(false);
        downStop.setVisible(true);
        downLabelStop.setText("");
        downLabelStart.setText("Start");
        downSecond.disable();
        downMinute.disable();
        downHour.disable();
        down = true;
        Thread thread;
        thread = new Thread() {

            @Override
            public void run() {
                int displaySecond;
                int displayMinutes;
                int displayHours;
                boolean x = true;

                if (downSecond.getText().isEmpty()) {
                    displaySecond = 0;
                } else {
                    displaySecond = Integer.parseInt(downSecond.getText());
                }

                if (downMinute.getText().isEmpty()) {
                    displayMinutes = 0;
                } else {
                    displayMinutes = Integer.parseInt(downMinute.getText());
                }

                if (downHour.getText().isEmpty()) {
                    displayHours = 0;
                } else {
                    displayHours = Integer.parseInt(downHour.getText());
                }

                if (displaySecond > 59) {
                    displayMinutes += (displaySecond / 60);
                    displaySecond %= 60;

                }
                if (displayMinutes > 59) {
                    displayHours += (displayMinutes / 60);
                    displayMinutes %= 60;

                }
                if (displaySecond == 0 && displayMinutes == 0 && displayHours == 0) {
                    System.out.println("Times Up!");
                    notify.setText("Times Up!");
                    downSecond.setText("00");
                    downMinute.setText("00");
                    downHour.setText("00");
                    this.stop();
                }

                while (x) {
                    if (down == true) {
                        try {
                            if (displaySecond < 10) {

                            }
                            downSecond.setText(Integer.toString((int) displaySecond));
                            downMinute.setText(Integer.toString((int) displayMinutes));
                            downHour.setText(Integer.toString((int) displayHours));
                            sleep(1000);
                            if (displaySecond > 0) {
                                displaySecond--;
                            } else {
                                displaySecond = 59;
                                displayMinutes--;
                                if (displayMinutes < 0) {
                                    displayMinutes = 59;
                                    displayHours--;
                                }
                            }

                            if (displaySecond == 0 && displayMinutes == 0 && displayHours == 0) {
                                System.out.println("Times Up!");
                                notify.setText("Times Up!");
                                downSecond.setText("00");
                                downMinute.setText("00");
                                downHour.setText("00");
                                this.stop();
                            }

                            downSecond.setText(Integer.toString((int) displaySecond));
                            downMinute.setText(Integer.toString((int) displayMinutes));
                            downHour.setText(Integer.toString((int) displayHours));

                        } catch (InterruptedException ex) {
                            Logger.getLogger(FourNOne_TimeApp.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                }
            }

        };
        thread.start();

    }//GEN-LAST:event_downStartActionPerformed

    private void downStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downStopActionPerformed
        // TODO add your handling code here:
        down = false;
        downStop.setVisible(false);
        downStart.setVisible(true);
        downLabelStop.setText("Stop");
        downLabelStart.setText("");
        notify.setText("");
        downSecond.enable();
        downMinute.enable();
        downHour.enable();
    }//GEN-LAST:event_downStopActionPerformed

    private void upStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upStartActionPerformed

    private void upStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upStopActionPerformed

    private void stopwatchStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopwatchStartMouseClicked
        stopwatchStart.setVisible(false);
        stopwatchStop.setVisible(true);
        stopwatchLabelStop.setText("");
        stopwatchLabelStart.setText("Start");
        watch = true;
        jLabelStopWatch.setText("00:00:00");
        Thread thread;
        thread = new Thread() {

            @Override
            public void run() {

                boolean x = true;
                long displayMinutes = 0;
                long displayHours = 0;
                long starttime = System.currentTimeMillis();
                System.out.println(displayHours + ":" + displayMinutes + ":0");

                while (x) {
                    if (watch == true) {
                        try {
                            sleep(1000);
                            long timepassed = System.currentTimeMillis() - starttime;
                            long secondspassed = timepassed / 1000;
                            if (secondspassed == 60) {
                                displayMinutes++;
                                secondspassed = 0;
                                starttime = System.currentTimeMillis();
                            }
                            if (displayMinutes == 60) {
                                displayMinutes = 0;
                                displayHours++;
                            }
                            if (displayHours == 24) {
                                displayHours = 0;
                                displayMinutes = 0;
                                secondspassed = 0;
                                starttime = System.currentTimeMillis();
                            }
                            jLabelStopWatch.setText(displayHours + ":" + displayMinutes + ":" + secondspassed);
                            System.out.println(displayHours + ":" + displayMinutes + ":" + secondspassed);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(FourNOne_TimeApp.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                }
            }

        };
        thread.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_stopwatchStartMouseClicked

    private void jLabelCurrentTimePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelCurrentTimePropertyChange

        Thread th = new Thread() {

            @Override
            public void run() {
                final DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
                for (;;) {
                    try {
                        sleep(1000);
                        Calendar now = Calendar.getInstance();
                        jLabelCurrentTime.setText(dateFormat.format(now.getTime()));
                        System.out.println(dateFormat.format(now.getTime()));
                    } catch (InterruptedException ex) {
                        Logger.getLogger(FourNOne_TimeApp.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

        };
        th.start();

    }//GEN-LAST:event_jLabelCurrentTimePropertyChange

    private void none(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_none


    }//GEN-LAST:event_none

    private void downMinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downMinuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downMinuteActionPerformed

    private void downSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downSecondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downSecondActionPerformed

    private void downHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downHourActionPerformed

    private void upStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upStartMouseClicked
        countup = 0;
        up = true;
        upStart.setVisible(false);
        upStop.setVisible(true);
        upLabelStop.setText("");
        upLabelStart.setText("Start");
        Thread d = new Thread() {

            @Override
            public void run() {
                for (;;) {
                    if (up == true) {
                        try {
                            sleep(800);
                            upCount.setText("" + countup + "");
                            countup++;
                        } catch (InterruptedException ex) {
                            Logger.getLogger(FourNOne_TimeApp.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }
            }

        };
        d.start();

    }//GEN-LAST:event_upStartMouseClicked

    private void upStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upStopMouseClicked

        up = false;
        upStop.setVisible(false);
        upStart.setVisible(true);
        upLabelStop.setText("Stop");
        upLabelStart.setText("");
    }//GEN-LAST:event_upStopMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FourNOne_TimeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FourNOne_TimeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FourNOne_TimeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FourNOne_TimeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FourNOne_TimeApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JPanel Jpanel2;
    private javax.swing.JPanel Jpanel3;
    private javax.swing.JPanel Jpanel4;
    private javax.swing.JTextField downHour;
    private javax.swing.JLabel downLabelStart;
    private javax.swing.JLabel downLabelStop;
    private javax.swing.JTextField downMinute;
    private javax.swing.JTextField downSecond;
    private javax.swing.JButton downStart;
    private javax.swing.JButton downStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCurrentTime;
    private javax.swing.JLabel jLabelStopWatch;
    private javax.swing.JLabel notify;
    private javax.swing.JLabel stopwatchLabelStart;
    private javax.swing.JLabel stopwatchLabelStop;
    private javax.swing.JButton stopwatchStart;
    private javax.swing.JButton stopwatchStop;
    private javax.swing.JLabel upCount;
    private javax.swing.JLabel upLabelStart;
    private javax.swing.JLabel upLabelStop;
    private javax.swing.JButton upStart;
    private javax.swing.JButton upStop;
    // End of variables declaration//GEN-END:variables
}
