/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FilteringWordTag;

import StringManipulation.FilterHTML;
import java.io.File;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author debuayanri_sd2082
 */
public class Remove_HTML_Tag extends javax.swing.JFrame {

    FilterHTML s = new FilterHTML();

    /**
     * Creates new form NewJFrame
     */
    public Remove_HTML_Tag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOrig = new javax.swing.JTextArea();
        removeTagsButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFiltered = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2WordCount = new javax.swing.JButton();
        jButton2OpenFile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2CountHTMLTags = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Technological and Enterprise University App");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextAreaOrig.setColumns(20);
        jTextAreaOrig.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOrig);

        removeTagsButton.setText("Remove HTML Tags");
        removeTagsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeTagsButtonMouseClicked(evt);
            }
        });
        removeTagsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTagsButtonActionPerformed(evt);
            }
        });

        jTextAreaFiltered.setColumns(20);
        jTextAreaFiltered.setRows(5);
        jScrollPane2.setViewportView(jTextAreaFiltered);

        jLabel1.setText("RESULT");

        jButton2WordCount.setText("Word Count");
        jButton2WordCount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2WordCountMouseClicked(evt);
            }
        });
        jButton2WordCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2WordCountActionPerformed(evt);
            }
        });

        jButton2OpenFile.setForeground(new java.awt.Color(0, 102, 102));
        jButton2OpenFile.setText("Open school.txt file");
        jButton2OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2OpenFileActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("<<--Click to open html file");

        jButton2CountHTMLTags.setText("Count HTML Tags");
        jButton2CountHTMLTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CountHTMLTagsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(removeTagsButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2WordCount)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2CountHTMLTags))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2OpenFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2OpenFile)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeTagsButton)
                            .addComponent(jButton2WordCount)
                            .addComponent(jButton2CountHTMLTags))
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeTagsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTagsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeTagsButtonActionPerformed

    private void removeTagsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeTagsButtonMouseClicked
        String str = jTextAreaOrig.getText();
        str = s.removeTags(str);
        jTextAreaFiltered.setText(str);
    }//GEN-LAST:event_removeTagsButtonMouseClicked

    private void jButton2WordCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2WordCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2WordCountActionPerformed

    private void jButton2WordCountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2WordCountMouseClicked
        jTextAreaFiltered.setText("processing!");
        String str = jTextAreaOrig.getText();
        str = s.countWords(str);
        jTextAreaFiltered.setText(str);

    }//GEN-LAST:event_jButton2WordCountMouseClicked

    private void jButton2OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2OpenFileActionPerformed
        // TODO add your handling code here:
        final JFrame f = new JFrame("Document Viewer");
        final JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        fileChooser.setFileFilter(filter);
        final JEditorPane document = new JEditorPane();

        int result = fileChooser.showOpenDialog(f);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                document.setPage(file.toURI().toURL());
                jTextAreaFiltered.setText(file.getName());
                String str = jTextAreaFiltered.getText();
                s.schoolName = str.substring(0, str.length() - 4);
                jLabel2.setText("You have selected " + s.schoolName.toUpperCase() + " !");
                jTextAreaOrig.setText(document.getText());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jButton2OpenFileActionPerformed

    private void jButton2CountHTMLTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CountHTMLTagsActionPerformed
        // TODO add your handling code here:
        String str = jTextAreaOrig.getText();
        str = s.countTags(str);
        jTextAreaFiltered.setText(str);
    }//GEN-LAST:event_jButton2CountHTMLTagsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remove_HTML_Tag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remove_HTML_Tag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remove_HTML_Tag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remove_HTML_Tag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Remove_HTML_Tag().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2CountHTMLTags;
    private javax.swing.JButton jButton2OpenFile;
    private javax.swing.JButton jButton2WordCount;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaFiltered;
    private javax.swing.JTextArea jTextAreaOrig;
    private javax.swing.JButton removeTagsButton;
    // End of variables declaration//GEN-END:variables
}
